[package]
name = "cancancan-diesel"
version.workspace = true
edition = "2024"
rust-version = "1.85"
license = "MIT"

[dependencies]
cancancan-core = { path = "../cancancan-core" }
diesel = { workspace = true }
diesel-dynamic-schema = "0.2.3"

[dev-dependencies]
rstest.workspace = true
diesel = { workspace = true, features = ["sqlite"] }
libsqlite3-sys = { version = "0.28", features = ["bundled"] }

[features]
default = []
sqlite = ["diesel/sqlite", "diesel-dynamic-schema/sqlite"]
postgres = ["diesel/postgres", "diesel-dynamic-schema/postgres"]

[lints]
workspace = true
